// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tanakh.Infrastructure.Data;

#nullable disable

namespace Tanakh.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260730141802_ReadingProgress")]
    partial class ReadingProgress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tanakh.Domain.Entities.ReadingProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Book")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("book");

                    b.Property<int>("Chapter")
                        .HasColumnType("integer")
                        .HasColumnName("chapter");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("section");

                    b.Property<Guid>("SubscriberId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscriber_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("Verse")
                        .HasColumnType("integer")
                        .HasColumnName("verse");

                    b.HasKey("Id")
                        .HasName("pk_reading_progress");

                    b.HasIndex("SubscriberId", "Section")
                        .IsUnique()
                        .HasDatabaseName("ix_reading_progress_subscriber_id_section");

                    b.ToTable("reading_progress", null, t =>
                        {
                            t.HasCheckConstraint("ck_reading_progress_chapter", "chapter >= 1");

                            t.HasCheckConstraint("ck_reading_progress_section", "section IN ('torah','neviim','ketuvim')");

                            t.HasCheckConstraint("ck_reading_progress_verse", "verse IS NULL OR verse >= 1");
                        });
                });

            modelBuilder.Entity("Tanakh.Domain.Entities.Subscriber", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("he-IL")
                        .HasColumnName("locale");

                    b.Property<TimeOnly>("PreferredTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("preferred_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Asia/Jerusalem")
                        .HasColumnName("timezone");

                    b.Property<string>("UnsubscribeReason")
                        .HasColumnType("text")
                        .HasColumnName("unsubscribe_reason");

                    b.Property<DateTimeOffset?>("UnsubscribedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unsubscribed_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_subscribers");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_subscribers_email");

                    b.ToTable("subscribers", null, t =>
                        {
                            t.HasCheckConstraint("ck_subscribers_status", "status IN ('pending_confirmation','active','unsubscribed','bounced','complained')");

                            t.HasCheckConstraint("ck_subscribers_timezone_not_empty", "length(trim(timezone)) > 0");
                        });
                });

            modelBuilder.Entity("Tanakh.Domain.Entities.ReadingProgress", b =>
                {
                    b.HasOne("Tanakh.Domain.Entities.Subscriber", null)
                        .WithMany()
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reading_progress_subscribers_subscriber_id");
                });
#pragma warning restore 612, 618
        }
    }
}
