// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tanakh.Infrastructure.Data;

#nullable disable

namespace Tanakh.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260730191612_SubscriberPausedUntil")]
    partial class SubscriberPausedUntil
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tanakh.Domain.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpHash")
                        .HasColumnType("text")
                        .HasColumnName("ip_hash");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("At")
                        .IsDescending()
                        .HasDatabaseName("ix_audit_log_at");

                    b.HasIndex("EntityId", "At")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_log_entity_id_at");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("Tanakh.Domain.Entities.ConfirmationToken", b =>
                {
                    b.Property<string>("TokenHash")
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("purpose");

                    b.Property<Guid>("SubscriberId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscriber_id");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("TokenHash")
                        .HasName("pk_confirmation_tokens");

                    b.HasIndex("SubscriberId")
                        .HasDatabaseName("ix_confirmation_tokens_subscriber_id");

                    b.ToTable("confirmation_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_confirmation_tokens_purpose", "purpose IN ('confirm')");
                        });
                });

            modelBuilder.Entity("Tanakh.Domain.Entities.ConsentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConsentType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("consent_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Granted")
                        .HasColumnType("boolean")
                        .HasColumnName("granted");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<string>("IpHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip_hash");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("policy_version");

                    b.Property<Guid>("SubscriberId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscriber_id");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_consent_records");

                    b.HasIndex("SubscriberId", "ConsentType", "GrantedAt")
                        .HasDatabaseName("ix_consent_records_subscriber_id_consent_type_granted_at");

                    b.ToTable("consent_records", null, t =>
                        {
                            t.HasCheckConstraint("ck_consent_records_consent_type", "consent_type IN ('marketing','analytics','functional')");
                        });
                });

            modelBuilder.Entity("Tanakh.Domain.Entities.EmailEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BounceType")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("bounce_type");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_event_id");

                    b.Property<string>("ProviderMessageId")
                        .HasColumnType("text")
                        .HasColumnName("provider_message_id");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<Guid?>("SubscriberId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscriber_id");

                    b.HasKey("Id")
                        .HasName("pk_email_events");

                    b.HasIndex("ProviderEventId")
                        .IsUnique()
                        .HasDatabaseName("ix_email_events_provider_event_id");

                    b.HasIndex("ProviderMessageId")
                        .HasDatabaseName("ix_email_events_provider_message_id");

                    b.HasIndex("SubscriberId")
                        .HasDatabaseName("ix_email_events_subscriber_id");

                    b.ToTable("email_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_email_events_bounce_type", "bounce_type IS NULL OR bounce_type IN ('hard','soft')");

                            t.HasCheckConstraint("ck_email_events_event_type", "event_type IN ('delivered','bounce','complaint','open')");
                        });
                });

            modelBuilder.Entity("Tanakh.Domain.Entities.ReadingProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Book")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("book");

                    b.Property<int>("Chapter")
                        .HasColumnType("integer")
                        .HasColumnName("chapter");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("section");

                    b.Property<Guid>("SubscriberId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscriber_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("Verse")
                        .HasColumnType("integer")
                        .HasColumnName("verse");

                    b.HasKey("Id")
                        .HasName("pk_reading_progress");

                    b.HasIndex("SubscriberId", "Section")
                        .IsUnique()
                        .HasDatabaseName("ix_reading_progress_subscriber_id_section");

                    b.ToTable("reading_progress", null, t =>
                        {
                            t.HasCheckConstraint("ck_reading_progress_chapter", "chapter >= 1");

                            t.HasCheckConstraint("ck_reading_progress_section", "section IN ('torah','neviim','ketuvim')");

                            t.HasCheckConstraint("ck_reading_progress_verse", "verse IS NULL OR verse >= 1");
                        });
                });

            modelBuilder.Entity("Tanakh.Domain.Entities.ReminderDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("ProviderMessageId")
                        .HasColumnType("text")
                        .HasColumnName("provider_message_id");

                    b.Property<DateTimeOffset>("ScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubscriberId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscriber_id");

                    b.Property<string>("TargetUrl")
                        .HasColumnType("text")
                        .HasColumnName("target_url");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_reminder_deliveries");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_reminder_deliveries_idempotency_key");

                    b.HasIndex("Status", "ScheduledFor")
                        .HasDatabaseName("ix_reminder_deliveries_status_scheduled_for");

                    b.HasIndex("SubscriberId", "ScheduledFor")
                        .IsUnique()
                        .HasDatabaseName("ix_reminder_deliveries_subscriber_id_scheduled_for");

                    b.ToTable("reminder_deliveries", null, t =>
                        {
                            t.HasCheckConstraint("ck_reminder_deliveries_status", "status IN ('pending','sending','sent','failed','skipped')");
                        });
                });

            modelBuilder.Entity("Tanakh.Domain.Entities.Subscriber", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("he-IL")
                        .HasColumnName("locale");

                    b.Property<DateTimeOffset?>("PausedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paused_until");

                    b.Property<TimeOnly>("PreferredTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("preferred_time");

                    b.Property<bool>("SkipShabbatHolidays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("skip_shabbat_holidays");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Asia/Jerusalem")
                        .HasColumnName("timezone");

                    b.Property<string>("UnsubscribeReason")
                        .HasColumnType("text")
                        .HasColumnName("unsubscribe_reason");

                    b.Property<DateTimeOffset?>("UnsubscribedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unsubscribed_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_subscribers");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_subscribers_email");

                    b.ToTable("subscribers", null, t =>
                        {
                            t.HasCheckConstraint("ck_subscribers_status", "status IN ('pending_confirmation','active','unsubscribed','bounced','complained')");

                            t.HasCheckConstraint("ck_subscribers_timezone_not_empty", "length(trim(timezone)) > 0");
                        });
                });

            modelBuilder.Entity("Tanakh.Domain.Entities.SuppressionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EmailHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_hash");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("reason");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_suppression_list");

                    b.HasIndex("EmailHash")
                        .IsUnique()
                        .HasDatabaseName("ix_suppression_list_email_hash");

                    b.ToTable("suppression_list", null, t =>
                        {
                            t.HasCheckConstraint("ck_suppression_list_reason", "reason IN ('hard_bounce','complaint','manual','unsubscribe')");
                        });
                });

            modelBuilder.Entity("Tanakh.Domain.Entities.ConfirmationToken", b =>
                {
                    b.HasOne("Tanakh.Domain.Entities.Subscriber", null)
                        .WithMany()
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_confirmation_tokens_subscribers_subscriber_id");
                });

            modelBuilder.Entity("Tanakh.Domain.Entities.ConsentRecord", b =>
                {
                    b.HasOne("Tanakh.Domain.Entities.Subscriber", null)
                        .WithMany()
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_consent_records_subscribers_subscriber_id");
                });

            modelBuilder.Entity("Tanakh.Domain.Entities.EmailEvent", b =>
                {
                    b.HasOne("Tanakh.Domain.Entities.Subscriber", null)
                        .WithMany()
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_email_events_subscribers_subscriber_id");
                });

            modelBuilder.Entity("Tanakh.Domain.Entities.ReadingProgress", b =>
                {
                    b.HasOne("Tanakh.Domain.Entities.Subscriber", null)
                        .WithMany()
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reading_progress_subscribers_subscriber_id");
                });

            modelBuilder.Entity("Tanakh.Domain.Entities.ReminderDelivery", b =>
                {
                    b.HasOne("Tanakh.Domain.Entities.Subscriber", null)
                        .WithMany()
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reminder_deliveries_subscribers_subscriber_id");
                });
#pragma warning restore 612, 618
        }
    }
}
