// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tanakh.Infrastructure.Data;

#nullable disable

namespace Tanakh.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260805230413_AddAppSettingsAndFeatureFlags")]
    partial class AddAppSettingsAndFeatureFlags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tanakh.Domain.Entities.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value_json");

                    b.HasKey("Key")
                        .HasName("pk_app_settings");

                    b.ToTable("app_settings", (string)null);
                });

            modelBuilder.Entity("Tanakh.Domain.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpHash")
                        .HasColumnType("text")
                        .HasColumnName("ip_hash");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("At")
                        .IsDescending()
                        .HasDatabaseName("ix_audit_log_at");

                    b.HasIndex("EntityId", "At")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_log_entity_id_at");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("Tanakh.Domain.Entities.ConsentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConsentType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("consent_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Granted")
                        .HasColumnType("boolean")
                        .HasColumnName("granted");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<string>("IpHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip_hash");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("policy_version");

                    b.Property<Guid>("SubscriberId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscriber_id");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_consent_records");

                    b.HasIndex("SubscriberId", "ConsentType", "GrantedAt")
                        .HasDatabaseName("ix_consent_records_subscriber_id_consent_type_granted_at");

                    b.ToTable("consent_records", null, t =>
                        {
                            t.HasCheckConstraint("ck_consent_records_consent_type", "consent_type IN ('marketing','analytics','functional')");
                        });
                });

            modelBuilder.Entity("Tanakh.Domain.Entities.ErrorLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Endpoint")
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<bool>("Resolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("resolved");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text")
                        .HasColumnName("stack_trace");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.HasKey("Id")
                        .HasName("pk_error_log");

                    b.HasIndex("Resolved", "Level", "CreatedAt")
                        .HasDatabaseName("ix_error_log_resolved_level_created_at");

                    b.ToTable("error_log", null, t =>
                        {
                            t.HasCheckConstraint("ck_error_log_level", "level IN ('info','warn','error','fatal')");
                        });
                });

            modelBuilder.Entity("Tanakh.Domain.Entities.FeatureFlag", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("enabled");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Name")
                        .HasName("pk_feature_flags");

                    b.ToTable("feature_flags", (string)null);
                });

            modelBuilder.Entity("Tanakh.Domain.Entities.OtpCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("Used")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("used");

                    b.HasKey("Id")
                        .HasName("pk_otp_codes");

                    b.HasIndex("Used", "ExpiresAt")
                        .HasDatabaseName("ix_otp_codes_used_expires_at");

                    b.ToTable("otp_codes", null, t =>
                        {
                            t.HasCheckConstraint("ck_otp_codes_attempts", "attempts <= 3");
                        });
                });

            modelBuilder.Entity("Tanakh.Domain.Entities.ReadingProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Book")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("book");

                    b.Property<int>("Chapter")
                        .HasColumnType("integer")
                        .HasColumnName("chapter");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("section");

                    b.Property<Guid>("SubscriberId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscriber_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("Verse")
                        .HasColumnType("integer")
                        .HasColumnName("verse");

                    b.HasKey("Id")
                        .HasName("pk_reading_progress");

                    b.HasIndex("SubscriberId", "Section")
                        .IsUnique()
                        .HasDatabaseName("ix_reading_progress_subscriber_id_section");

                    b.ToTable("reading_progress", null, t =>
                        {
                            t.HasCheckConstraint("ck_reading_progress_chapter", "chapter >= 1");

                            t.HasCheckConstraint("ck_reading_progress_section", "section IN ('torah','neviim','ketuvim')");

                            t.HasCheckConstraint("ck_reading_progress_verse", "verse IS NULL OR verse >= 1");
                        });
                });

            modelBuilder.Entity("Tanakh.Domain.Entities.ReminderDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("MessageBody")
                        .HasColumnType("text")
                        .HasColumnName("message_body");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("ProviderMessageId")
                        .HasColumnType("text")
                        .HasColumnName("provider_message_id");

                    b.Property<string>("ProviderResponse")
                        .HasColumnType("text")
                        .HasColumnName("provider_response");

                    b.Property<int?>("ProviderStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("provider_status_code");

                    b.Property<DateTimeOffset>("ScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for");

                    b.Property<int?>("SegmentCount")
                        .HasColumnType("integer")
                        .HasColumnName("segment_count");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubscriberId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscriber_id");

                    b.Property<string>("TargetUrl")
                        .HasColumnType("text")
                        .HasColumnName("target_url");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_reminder_deliveries");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_reminder_deliveries_idempotency_key");

                    b.HasIndex("Status", "ScheduledFor")
                        .HasDatabaseName("ix_reminder_deliveries_status_scheduled_for");

                    b.HasIndex("SubscriberId", "ScheduledFor")
                        .IsUnique()
                        .HasDatabaseName("ix_reminder_deliveries_subscriber_id_scheduled_for");

                    b.ToTable("reminder_deliveries", null, t =>
                        {
                            t.HasCheckConstraint("ck_reminder_deliveries_status", "status IN ('pending','sending','sent','failed','skipped')");
                        });
                });

            modelBuilder.Entity("Tanakh.Domain.Entities.SmsLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("ProviderResponse")
                        .HasColumnType("text")
                        .HasColumnName("provider_response");

                    b.Property<int?>("ProviderStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("provider_status_code");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<string>("ToPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("to_phone_number");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_sms_log");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_sms_log_created_at");

                    b.ToTable("sms_log", null, t =>
                        {
                            t.HasCheckConstraint("ck_sms_log_type", "type IN ('reminder','otp','test')");
                        });
                });

            modelBuilder.Entity("Tanakh.Domain.Entities.Subscriber", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("he-IL")
                        .HasColumnName("locale");

                    b.Property<DateTimeOffset?>("PausedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paused_until");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<TimeOnly>("PreferredTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("preferred_time");

                    b.Property<bool>("SkipShabbatHolidays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("skip_shabbat_holidays");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Asia/Jerusalem")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset?>("UnsubscribedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unsubscribed_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_subscribers");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_subscribers_phone_number");

                    b.ToTable("subscribers", null, t =>
                        {
                            t.HasCheckConstraint("ck_subscribers_phone_required_when_active", "status <> 'active' OR phone_number IS NOT NULL");

                            t.HasCheckConstraint("ck_subscribers_status", "status IN ('active','unsubscribed')");

                            t.HasCheckConstraint("ck_subscribers_timezone_not_empty", "length(trim(timezone)) > 0");
                        });
                });

            modelBuilder.Entity("Tanakh.Domain.Entities.ConsentRecord", b =>
                {
                    b.HasOne("Tanakh.Domain.Entities.Subscriber", null)
                        .WithMany()
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_consent_records_subscribers_subscriber_id");
                });

            modelBuilder.Entity("Tanakh.Domain.Entities.ReadingProgress", b =>
                {
                    b.HasOne("Tanakh.Domain.Entities.Subscriber", null)
                        .WithMany()
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reading_progress_subscribers_subscriber_id");
                });

            modelBuilder.Entity("Tanakh.Domain.Entities.ReminderDelivery", b =>
                {
                    b.HasOne("Tanakh.Domain.Entities.Subscriber", null)
                        .WithMany()
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reminder_deliveries_subscribers_subscriber_id");
                });
#pragma warning restore 612, 618
        }
    }
}
